
import Script from 'next/script'
import Footer from '@/components/footer'
import './globals.css'
import Navbar from '@/components/navbar'
import Carousel from '@/components/carousel'
import { AOS_URL, SCRIPT_DATA, STYLE_URL } from '@/utils/constant'
import AOS from 'aos';
import 'aos/dist/aos.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href={STYLE_URL} defer/>
      <script src={SCRIPT_DATA} defer />
      </head>
      <body>
      <Navbar/>
      <Carousel/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
